# Generated by Django 3.1.3 on 2021-05-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avaliable',
            field=models.BooleanField(default=True),
        ),
    ]
